export const endpoints = [
  {
    name: "Get Users",
    url: `${process.env.TEST_API_BASE}/users`,
    expectedStatus: 200,
    expectedFields: ["id", "name", "email"],
    expectedTypes: {
      id: "number",
      name: "string",
      email: "string",
    },
    requiresAuth: false,
  },
  {
    name: "Get All Posts",
    url: `${process.env.TEST_API_BASE}/posts`,
    expectedStatus: 200,
    expectedFields: ["id", "title", "body", "userId"],
    expectedTypes: {
      id: "number",
      title: "string",
      body: "string",
      userId: "number",
    },
    requiresAuth: false,
  },
  {
    name: "Get Single Post",
    url: `${process.env.TEST_API_BASE}/posts/1`,
    expectedStatus: 200,
    expectedFields: ["id", "title", "body", "userId"],
    expectedTypes: {
      id: "number",
      title: "string",
      body: "string",
      userId: "number",
    },
    requiresAuth: false,
  },
  {
    name: "Get Post Comments",
    url: `${process.env.TEST_API_BASE}/posts/1/comments`,
    expectedStatus: 200,
    expectedFields: ["id", "name", "email", "body"],
    expectedTypes: {
      id: "number",
      name: "string",
      email: "string",
      body: "string",
    },
    requiresAuth: false,
  },
  {
    name: "Get Non-existent Post",
    url: `${process.env.TEST_API_BASE}/posts/999`,
    expectedStatus: 404,
    expectedFields: [],
    expectedTypes: {},
    requiresAuth: false,
  },
];
