export const endpoints = [
  {
    name: "Homepage Selection",
    group: "Homepage",
    url: `${process.env.TEST_API_BASE}/api/homepage-selection`,
    expectedStatus: 200,
    expectedFields: ["configured", "featuredTitle", "heroArticles"],
    expectedTypes: {
      configured: "boolean",
      featuredTitle: "string",
      heroArticles: "object",
    },
    requiresAuth: false,
    expectNonEmpty: false,
    nestedFields: {},
  },
  {
    name: "Homepage Featured Categories",
    group: "Homepage",
    url: `${process.env.TEST_API_BASE}/api/categories?filters[isFeatured][$eq]=true&filters[parent][id][$null]=true&sort[0]=displayOrder:asc&status=published`,
    expectedStatus: 200,
    expectedFields: ["data", "meta"],
    expectedTypes: { data: "object", meta: "object" },
    requiresAuth: false,
    expectNonEmpty: true,
    nestedFields: { slug: "string", title: "string" },
  },
  {
    name: "Homepage Featured Articles",
    group: "Homepage",
    url: `${process.env.TEST_API_BASE}/api/articles?filters[isFeatured][$eq]=true&fields[0]=slug&fields[1]=title&fields[2]=titleEn&fields[3]=subtitle&fields[4]=summary&fields[5]=kind&fields[6]=authorName&fields[7]=categoryName&fields[8]=isFeatured&fields[9]=isShortEntry&fields[10]=readingMinutes&fields[11]=wordCount&fields[12]=legacyId&fields[13]=publishedAt&fields[14]=updatedAt&populate[coverImage]=true&populate[authors][fields][0]=name&status=published&sort[0]=publishedAt:desc&pagination[pageSize]=6`,
    expectedStatus: 200,
    expectedFields: ["data", "meta"],
    expectedTypes: { data: "object", meta: "object" },
    requiresAuth: false,
    expectNonEmpty: true,
    nestedFields: { slug: "string", title: "string", publishedAt: "string" },
  },
  {
    name: "Homepage Notable Figures Articles",
    group: "Homepage",
    url: `${process.env.TEST_API_BASE}/api/articles?filters[categories][slug][$eq]=notable-figures&fields[0]=slug&fields[1]=title&fields[2]=titleEn&fields[3]=subtitle&fields[4]=summary&fields[5]=kind&fields[6]=authorName&fields[7]=categoryName&fields[8]=isFeatured&fields[9]=isShortEntry&fields[10]=readingMinutes&fields[11]=wordCount&fields[12]=legacyId&fields[13]=publishedAt&fields[14]=updatedAt&populate[coverImage]=true&populate[authors][fields][0]=name&status=published&sort[0]=publishedAt:desc&pagination[pageSize]=4`,
    expectedStatus: 200,
    expectedFields: ["data", "meta"],
    expectedTypes: { data: "object", meta: "object" },
    requiresAuth: false,
    expectNonEmpty: true,
    nestedFields: { slug: "string", title: "string", publishedAt: "string" },
  },
  {
    name: "Article - Full Content",
    group: "Article",
    url: `${process.env.TEST_API_BASE}/api/articles?filters[slug][$eq]=karl-marks&populate[coverImage]=true&populate[images][populate][0]=file&populate[infobox]=true&populate[authors][populate][0]=photo&populate[keywords]=true&populate[categories][populate][0]=parent&status=published&pagination[pageSize]=1`,
    expectedStatus: 200,
    expectedFields: ["data", "meta"],
    expectedTypes: { data: "object", meta: "object" },
    requiresAuth: false,
    expectNonEmpty: true,
    nestedFields: { slug: "string", title: "string" },
  },
  {
    name: "Article - Comments",
    group: "Article",
    url: `${process.env.TEST_API_BASE}/api/comments?filters[article][slug][$eq]=karl-marks&filters[isHidden][$eq]=false&sort[0]=createdAt:desc&pagination[page]=1&pagination[pageSize]=50&pagination[withCount]=true&populate[author][fields][0]=username`,
    expectedStatus: 200,
    expectedFields: ["data", "meta"],
    expectedTypes: { data: "object", meta: "object" },
    requiresAuth: false,
    expectNonEmpty: false,
    nestedFields: {},
  },
  {
    name: "Article - Likes Count",
    group: "Article",
    url: `${process.env.TEST_API_BASE}/api/article-likes?filters[article][slug][$eq]=karl-marks&pagination[pageSize]=1&pagination[withCount]=true`,
    expectedStatus: 200,
    expectedFields: ["data", "meta"],
    expectedTypes: { data: "object", meta: "object" },
    requiresAuth: false,
    expectNonEmpty: false,
    nestedFields: {},
  },
  {
    name: "Article - Bookmarks Count",
    group: "Article",
    url: `${process.env.TEST_API_BASE}/api/article-bookmarks?filters[article][slug][$eq]=karl-marks&pagination[pageSize]=1&pagination[withCount]=true`,
    expectedStatus: 200,
    expectedFields: ["data", "meta"],
    expectedTypes: { data: "object", meta: "object" },
    requiresAuth: false,
    expectNonEmpty: false,
    nestedFields: {},
  },
  {
    name: "Article - Public Annotations",
    group: "Article",
    url: `${process.env.TEST_API_BASE}/api/annotations?filters[isPublic][$eq]=true&filters[article][slug][$eq]=karl-marks&pagination[pageSize]=20`,
    expectedStatus: 200,
    expectedFields: ["data", "meta"],
    expectedTypes: { data: "object", meta: "object" },
    requiresAuth: false,
    expectNonEmpty: false,
    nestedFields: {},
  },
  {
    name: "Article - Approved Links",
    group: "Article",
    url: `${process.env.TEST_API_BASE}/api/approved-article-links?filters[sourceArticle][slug][$eq]=karl-marks&pagination[pageSize]=20`,
    expectedStatus: 200,
    expectedFields: ["data", "meta"],
    expectedTypes: { data: "object", meta: "object" },
    requiresAuth: false,
    expectNonEmpty: false,
    nestedFields: {},
  },
  {
    name: "Article - Topic Assignments",
    group: "Article",
    url: `${process.env.TEST_API_BASE}/api/article-topic-assignments?filters[article][slug][$eq]=karl-marks&pagination[pageSize]=20`,
    expectedStatus: 200,
    expectedFields: ["data", "meta"],
    expectedTypes: { data: "object", meta: "object" },
    requiresAuth: false,
    expectNonEmpty: false,
    nestedFields: {},
  },
  {
    name: "Article - Version Events",
    group: "Article",
    url: `${process.env.TEST_API_BASE}/api/article-version-events?filters[article][slug][$eq]=karl-marks&sort[0]=createdAt:desc`,
    expectedStatus: 200,
    expectedFields: ["data", "meta"],
    expectedTypes: { data: "object", meta: "object" },
    requiresAuth: false,
    expectNonEmpty: false,
    nestedFields: {},
  },
  {
    name: "Article - Record View",
    group: "Article",
    url: `${process.env.TEST_API_BASE}/api/articles/karl-marks/view`,
    method: "POST",
    expectedStatus: 200,
    expectedFields: ["ok", "viewCount"],
    expectedTypes: { ok: "boolean", viewCount: "number" },
    requiresAuth: false,
    expectNonEmpty: false,
    nestedFields: {},
  },
  {
    name: "Article - Book Info",
    group: "Article",
    url: `${process.env.TEST_API_BASE}/api/articles/karl-marks/book`,
    expectedStatus: 200,
    expectedFields: [],
    expectedTypes: {},
    requiresAuth: false,
    expectNonEmpty: false,
    nestedFields: {},
  },
  {
    name: "Categories - Top Level",
    group: "Categories",
    url: `${process.env.TEST_API_BASE}/api/categories?filters[parent][id][$null]=true&sort[0]=displayOrder:asc&pagination[pageSize]=20&status=published`,
    expectedStatus: 200,
    expectedFields: ["data", "meta"],
    expectedTypes: { data: "object", meta: "object" },
    requiresAuth: false,
    expectNonEmpty: true,
    nestedFields: { slug: "string", title: "string" },
  },
  {
    name: "Categories - Subcategories by Parent",
    group: "Categories",
    url: `${process.env.TEST_API_BASE}/api/categories?filters[parent][slug][$eq]=geography&fields[0]=title&fields[1]=slug&pagination[pageSize]=50&status=published`,
    expectedStatus: 200,
    expectedFields: ["data", "meta"],
    expectedTypes: { data: "object", meta: "object" },
    requiresAuth: false,
    expectNonEmpty: true,
    nestedFields: { slug: "string", title: "string" },
  },
  {
    name: "Categories - Single Category",
    group: "Categories",
    url: `${process.env.TEST_API_BASE}/api/categories?filters[slug][$eq]=notable-figures&status=published`,
    expectedStatus: 200,
    expectedFields: ["data", "meta"],
    expectedTypes: { data: "object", meta: "object" },
    requiresAuth: false,
    expectNonEmpty: true,
    nestedFields: { slug: "string", title: "string" },
  },
  {
    name: "Categories - Articles by Category",
    group: "Categories",
    url: `${process.env.TEST_API_BASE}/api/articles?filters[categories][slug][$eq]=notable-figures&fields[0]=slug&fields[1]=title&fields[2]=titleEn&fields[3]=subtitle&fields[4]=summary&fields[5]=kind&fields[6]=authorName&fields[7]=categoryName&fields[8]=isFeatured&fields[9]=isShortEntry&fields[10]=readingMinutes&fields[11]=wordCount&fields[12]=legacyId&fields[13]=publishedAt&fields[14]=updatedAt&populate[coverImage]=true&populate[authors][fields][0]=name&status=published&sort[0]=publishedAt:desc&pagination[page]=1&pagination[pageSize]=48`,
    expectedStatus: 200,
    expectedFields: ["data", "meta"],
    expectedTypes: { data: "object", meta: "object" },
    requiresAuth: false,
    expectNonEmpty: true,
    nestedFields: { slug: "string", title: "string", publishedAt: "string" },
  },
  {
    name: "Search - Full Text Search",
    group: "Search",
    url: `${process.env.TEST_API_BASE}/api/articles-fts?q=%D9%85%D8%A7%D8%B1%D9%83%D8%B3`,
    expectedStatus: 200,
    expectedFields: ["data"],
    expectedTypes: { data: "object" },
    requiresAuth: false,
    expectNonEmpty: true,
    nestedFields: { slug: "string", title: "string" },
  },
  {
    name: "Search - Articles Contains",
    group: "Search",
    url: `${process.env.TEST_API_BASE}/api/articles?filters[$or][0][title][$containsi]=%D9%85%D8%A7%D8%B1%D9%83%D8%B3&filters[$or][1][summary][$containsi]=%D9%85%D8%A7%D8%B1%D9%83%D8%B3&fields[0]=title&fields[1]=slug&pagination[pageSize]=10&status=published`,
    expectedStatus: 200,
    expectedFields: ["data", "meta"],
    expectedTypes: { data: "object", meta: "object" },
    requiresAuth: false,
    expectNonEmpty: true,
    nestedFields: { slug: "string", title: "string" },
  },
  {
    name: "Search - AI Search",
    group: "Search",
    url: `${process.env.TEST_API_BASE}/api/articles-ai-search?q=%D9%85%D9%86%20%D9%87%D9%88%20%D9%83%D8%A7%D8%B1%D9%84%20%D9%85%D8%A7%D8%B1%D9%83%D8%B3`,
    expectedStatus: 200,
    expectedFields: ["ok", "query", "answer", "confidence"],
    expectedTypes: {
      ok: "boolean",
      query: "string",
      answer: "string",
      confidence: "string",
    },
    requiresAuth: false,
    expectNonEmpty: false,
    nestedFields: {},
  },
  {
    name: "All Articles",
    group: "All Articles",
    url: `${process.env.TEST_API_BASE}/api/articles?fields[0]=slug&fields[1]=title&fields[2]=titleEn&fields[3]=subtitle&fields[4]=summary&fields[5]=kind&fields[6]=authorName&fields[7]=categoryName&fields[8]=isFeatured&fields[9]=isShortEntry&fields[10]=readingMinutes&fields[11]=wordCount&fields[12]=legacyId&fields[13]=publishedAt&fields[14]=updatedAt&populate[coverImage]=true&populate[authors][fields][0]=name&status=published&sort[0]=publishedAt:desc&pagination[page]=1&pagination[pageSize]=30`,
    expectedStatus: 200,
    expectedFields: ["data", "meta"],
    expectedTypes: { data: "object", meta: "object" },
    requiresAuth: false,
    expectNonEmpty: true,
    nestedFields: { slug: "string", title: "string", publishedAt: "string" },
  },
  {
    name: "Author - Single Author",
    group: "Author",
    url: `${process.env.TEST_API_BASE}/api/authors?filters[slug][$eq]=elsayed-yousef&status=published`,
    expectedStatus: 200,
    expectedFields: ["data", "meta"],
    expectedTypes: { data: "object", meta: "object" },
    requiresAuth: false,
    expectNonEmpty: true,
    nestedFields: { slug: "string", name: "string" },
  },
  {
    name: "Author - Articles by Author",
    group: "Author",
    url: `${process.env.TEST_API_BASE}/api/articles?filters[authors][slug][$eq]=elsayed-yousef&fields[0]=slug&fields[1]=title&fields[2]=titleEn&fields[3]=subtitle&fields[4]=summary&fields[5]=kind&fields[6]=authorName&fields[7]=categoryName&fields[8]=isFeatured&fields[9]=isShortEntry&fields[10]=readingMinutes&fields[11]=wordCount&fields[12]=legacyId&fields[13]=publishedAt&fields[14]=updatedAt&populate[coverImage]=true&populate[authors][fields][0]=name&status=published&sort[0]=publishedAt:desc&pagination[pageSize]=24`,
    expectedStatus: 200,
    expectedFields: ["data", "meta"],
    expectedTypes: { data: "object", meta: "object" },
    requiresAuth: false,
    expectNonEmpty: false,
    nestedFields: {},
  },
  // Reader interaction endpoints (require JWT)
  {
    name: "Reader - My Account",
    group: "Reader",
    url: `${process.env.TEST_API_BASE}/api/users/me`,
    expectedStatus: 200,
    expectedFields: ["id", "username", "email"],
    expectedTypes: { id: "number", username: "string", email: "string" },
    requiresAuth: true,
    expectNonEmpty: false,
    nestedFields: {},
  },
  {
    name: "Reader - Like Toggle",
    group: "Reader",
    url: `${process.env.TEST_API_BASE}/api/article-likes/on-article/wgb857bh4378zgamowdfkpkf/toggle`,
    method: "POST",
    expectedStatus: 200,
    expectedFields: [],
    expectedTypes: {},
    requiresAuth: true,
    expectNonEmpty: false,
    nestedFields: {},
  },
  {
    name: "Reader - Bookmark Toggle",
    group: "Reader",
    url: `${process.env.TEST_API_BASE}/api/article-bookmarks/on-article/wgb857bh4378zgamowdfkpkf/toggle`,
    method: "POST",
    expectedStatus: 200,
    expectedFields: [],
    expectedTypes: {},
    requiresAuth: true,
    expectNonEmpty: false,
    nestedFields: {},
  },
  {
    name: "Reader - Post Comment",
    group: "Reader",
    url: `${process.env.TEST_API_BASE}/api/comments/on-article/wgb857bh4378zgamowdfkpkf`,
    method: "POST",
    expectedStatus: 200,
    expectedFields: [],
    expectedTypes: {},
    requiresAuth: true,
    expectNonEmpty: false,
    nestedFields: {},
    body: { data: { body: "تعليق تجريبي" } },
  },
  // Writer interaction endpoints (require JWT)
  {
    name: "Writer - Author Identity",
    group: "Writer",
    url: `${process.env.TEST_API_BASE}/api/author-portal/me`,
    expectedStatus: 200,
    expectedFields: [],
    expectedTypes: {},
    requiresAuth: true,
    expectNonEmpty: false,
    nestedFields: {},
  },
  {
    name: "Writer - Author Articles",
    group: "Writer",
    url: `${process.env.TEST_API_BASE}/api/author-portal/articles`,
    expectedStatus: 200,
    expectedFields: [],
    expectedTypes: {},
    requiresAuth: true,
    expectNonEmpty: false,
    nestedFields: {},
  },
  {
    name: "Writer - Article Detail",
    group: "Writer",
    url: `${process.env.TEST_API_BASE}/api/author-portal/articles/karl-marks`,
    expectedStatus: 200,
    expectedFields: [],
    expectedTypes: {},
    requiresAuth: true,
    expectNonEmpty: false,
    nestedFields: {},
  },
  {
    name: "Writer - Reader Comments",
    group: "Writer",
    url: `${process.env.TEST_API_BASE}/api/author-portal/comments`,
    expectedStatus: 200,
    expectedFields: [],
    expectedTypes: {},
    requiresAuth: true,
    expectNonEmpty: false,
    nestedFields: {},
  },
  {
    name: "Writer - Reply to Comment",
    group: "Writer",
    url: `${process.env.TEST_API_BASE}/api/author-portal/comments/1/reply`,
    method: "POST",
    expectedStatus: 403,
    expectedFields: [],
    expectedTypes: {},
    requiresAuth: true,
    expectNonEmpty: false,
    nestedFields: {},
  },
  {
    name: "Writer - Article Heatmap",
    group: "Writer",
    url: `${process.env.TEST_API_BASE}/api/author-portal/heatmap/karl-marks`,
    expectedStatus: 403,
    expectedFields: [],
    expectedTypes: {},
    requiresAuth: true,
    expectNonEmpty: false,
    nestedFields: {},
  },
  {
    name: "Writer - Update Profile",
    group: "Writer",
    url: `${process.env.TEST_API_BASE}/api/author-portal/profile`,
    method: "PATCH",
    expectedStatus: 403,
    expectedFields: [],
    expectedTypes: {},
    requiresAuth: true,
    expectNonEmpty: false,
    nestedFields: {},
  },
  {
    name: "Writer - Annotations Inbox",
    group: "Writer",
    url: `${process.env.TEST_API_BASE}/api/doc-trackers/inbox`,
    expectedStatus: 200,
    expectedFields: [],
    expectedTypes: {},
    requiresAuth: true,
    expectNonEmpty: false,
    nestedFields: {},
  },
];
